export type SafetyType = 'suicide' | 'self_harm' | 'acute_danger';

export interface SafetyResult {
	flagged: boolean;
	type: SafetyType | null;
}

// Keyword patterns grouped by safety type.
// Each pattern is matched case-insensitively against the full message.
const PATTERNS: { type: SafetyType; patterns: RegExp[] }[] = [
	{
		type: 'suicide',
		patterns: [
			/\bsuicid/i,
			/\bsjälvmord/i,
			/\bta\s+mitt\s+liv/i,
			/\bta\s+livet\s+av\s+mig/i,
			/\binte\s+vill\s+leva/i,
			/\bvill\s+inte\s+leva/i,
			/\bvill\s+dö/i,
			/\bvill\s+vara\s+död/i,
			/\bönskar\s+att\s+jag\s+var\s+död/i,
			/\binte\s+orkar\s+längre/i,
			/\bingen\s+mening\s+att\s+leva/i,
			/\bkill\s+my\s*self/i,
			/\bend\s+(my|it\s+all)/i,
			/\bwant\s+to\s+die/i,
			/\bdon'?t\s+want\s+to\s+(be\s+alive|live)/i,
		]
	},
	{
		type: 'self_harm',
		patterns: [
			/\bsjälvskad/i,
			/\bskära\s+mig/i,
			/\bskär\s+mig/i,
			/\bskadar?\s+mig\s+själv/i,
			/\bgöra\s+mig\s+själv\s+illa/i,
			/\bhurt\s+my\s*self/i,
			/\bself[- ]?harm/i,
			/\bcutting\s+my\s*self/i,
		]
	},
	{
		type: 'acute_danger',
		patterns: [
			/\bvill\s+skada\s+(någon|henne|honom|dem|hen)/i,
			/\bvill\s+döda/i,
			/\btänker\s+döda/i,
			/\bplanerar\s+att\s+(döda|skada)/i,
			/\bhar\s+en\s+plan\s+att/i,
			/\bgoing\s+to\s+hurt/i,
			/\bgoing\s+to\s+kill/i,
		]
	}
];

/**
 * Scans a user message for crisis indicators.
 * This runs BEFORE the LLM processes the message.
 */
export function detectCrisis(message: string): SafetyResult {
	for (const group of PATTERNS) {
		for (const pattern of group.patterns) {
			if (pattern.test(message)) {
				return { flagged: true, type: group.type };
			}
		}
	}
	return { flagged: false, type: null };
}

/**
 * Returns the hardcoded crisis response template.
 * This is NEVER generated by the LLM.
 */
export function getCrisisResponse(): string {
	return `Det du beskriver låter väldigt tungt, och jag tar det på allvar.

Jag uppfattar att du har det väldigt svårt just nu. Det här är större än vad jag kan hjälpa med, och du förtjänar att prata med en riktig människa.

**Hjälp att nå:**

| Tjänst | Kontakt | Tillgänglighet |
|--------|---------|----------------|
| Mind Självmordslinjen | 90101 (tel), chat via mind.se | Dygnet runt |
| Jourhavande medmänniska | 08-702 16 80 | 21–06 varje natt |
| SOS Alarm | 112 | Dygnet runt |
| BRIS (under 18) | 116 111 | Dygnet runt |

**Internationellt:**
- Crisis Text Line — text HOME to 741741
- IASP kriscentra — iasp.info/resources/Crisis_Centres

Du kan alltid starta en ny session i Sortify när du känner dig redo. Just nu är det viktigaste att du når en människa som kan lyssna.`;
}
